version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    links:
      - php
    networks:
      - internal_network
      - external_network
    ports:
      - "8088:8088"
    volumes:
      - ./:/var/www/
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/conf.d:/etc/nginx/conf.d
      - ./teleimg.conf:/etc/nginx/teleimg.conf
  php:
    build: ./
    restart: always
    networks:
      - internal_network
      - external_network
    volumes:
      - ./:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf

networks:
  internal_network:
    internal: true
  external_network: